"""empty message

Revision ID: e097eaed2a56
Revises: 819a1fa9c05f
Create Date: 2019-10-23 07:56:20.340404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e097eaed2a56'
down_revision = '819a1fa9c05f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('want_to_publish', sa.String(length=128), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'want_to_publish')
    # ### end Alembic commands ###
